otto:
  api: 1
  tasks:
    - dev
  envs:
    VERSION: "$(git describe --tags --always --dirty 2>/dev/null || echo 'dev')"
    GIT_SHA: "$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"

tasks:
  # Development Setup
  dev:
    help: "Setup development environment (check Rust installation)"
    bash: |
      echo "🦀 Otto Development Environment"
      echo ""
      echo "Rust version:"
      rustc --version
      echo ""
      echo "Cargo version:"
      cargo --version
      echo ""
      echo "✅ Development environment ready!"
      echo ""
      echo "Quick commands:"
      echo "  cargo build          - Build debug"
      echo "  cargo test           - Run tests"
      echo "  cargo clippy         - Lint"
      echo "  cargo fmt            - Format"
      echo ""
      echo "Otto tasks:"
      echo "  otto ci              - Full CI pipeline"
      echo "  otto quick           - Fast validation"

  # Individual quality checks (for parallel execution)
  check:
    help: "Fast compile check"
    bash: |
      cargo check

  clippy:
    help: "Run Clippy linter"
    bash: |
      cargo clippy -- -D warnings

  fmt-check:
    help: "Check code formatting"
    bash: |
      cargo fmt -- --check

  test:
    help: "Run all tests"
    bash: |
      cargo test

  doc-build:
    help: "Build documentation"
    bash: |
      cargo doc --no-deps

  # Meta task: quick validation (3 things in parallel)
  quick:
    help: "Quick validation (check + test + fmt-check in parallel)"
    before: [check, test, fmt-check]
    bash: |
      echo "✅ Quick checks passed!"

  # Meta task: CI pipeline (3 checks in parallel)
  ci:
    help: "Full CI pipeline (test + clippy + fmt-check in parallel)"
    before: [test, clippy, fmt-check]
    bash: |
      echo "✅ All CI checks passed!"

  # Pre-commit workflow
  pre-commit:
    help: "Pre-commit checks (format, then run CI)"
    bash: |
      echo "=== Formatting Code ==="
      cargo fmt
      echo ""
      echo "=== Running CI Checks ==="
      otto ci
      echo ""
      echo "✅ Ready to commit!"

  # Examples
  validate-examples:
    help: "Validate all example ottofiles parse correctly"
    bash: |
      echo "Validating example ottofiles..."
      failed=0
      for dir in examples/*/; do
        if [ -f "$dir/otto.yml" ] || [ -f "$dir/otto.yaml" ] || [ -f "$dir/.otto.yml" ]; then
          echo -n "Checking $(basename $dir)... "
          if cargo run --quiet --manifest-path=./Cargo.toml -- -o "$dir" --help > /dev/null 2>&1; then
            echo "✅"
          else
            echo "❌"
            failed=$((failed + 1))
          fi
        fi
      done
      if [ $failed -eq 0 ]; then
        echo ""
        echo "✅ All examples valid!"
      else
        echo ""
        echo "❌ $failed example(s) failed validation"
        exit 1
      fi

  # Complete validation (4 things in parallel)
  all:
    help: "Run everything (ci + doc + examples in parallel)"
    before: [ci, doc-build, validate-examples]
    bash: |
      echo ""
      echo "=== Summary ==="
      echo "✅ All tests passed"
      echo "✅ Clippy checks passed"
      echo "✅ Format checks passed"
      echo "✅ Documentation built"
      echo "✅ Examples validated"
      echo ""
      echo "🎉 Everything looks great!"

  # Release workflow
  release-check:
    help: "Verify everything is ready for release"
    before: [all]
    bash: |
      echo ""
      echo "=== Release Checklist ==="
      echo "✅ All validations passed"
      echo ""
      echo "Current version: $(grep '^version =' Cargo.toml | cut -d'"' -f2)"
      echo "Git tag: $(git describe --tags --always)"
      echo ""
      echo "To release:"
      echo "  1. Update version in Cargo.toml"
      echo "  2. Commit changes"
      echo "  3. Tag: git tag v<version>"
      echo "  4. Push: git push && git push --tags"
      echo "  5. cargo publish"

  # Cleanup
  clean-all:
    help: "Deep clean (cargo clean + remove all otto run artifacts)"
    bash: |
      echo "Cleaning cargo artifacts..."
      cargo clean
      echo ""
      echo "Cleaning otto run directories..."
      rm -rf .otto-run/
      find examples/ -type d -name ".otto-run" -exec rm -rf {} + 2>/dev/null || true
      echo ""
      echo "✅ All cleaned!"
