otto:
  api: 1
  jobs: 12
  tasks:
  - sometask
tasks:
  sometask:
    action: |
      echo "Running sometask with parameters:"
      echo "  --opt1: ${opt1:-'(not provided)'}"
      echo "  --opt2: ${opt2}"
      echo "  positional argument: ${positional}"
      echo "Task completed successfully!"
    params:
      --opt1:
        metavar: OPT
        help: opt1 help message
      --opt2:
        dest: stored_name
        default: three
        choices:
        - one
        - two
        - three
        help: opt2 help message
      positional:
        default: 1
        choices:
        - 1
        - 2
        - 3
        help: help message
